config/routes.rb
Wacomxs::Application.routes.draw do
	resources :recommendations
	root :to => 'home#index'

	match 'download/:id' => 'download#main'
	match 'download/raw/:id' => 'download#raw'

	match '*path' => 'home#index'

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
	attr_accessible \
		:title,
		:buttons,
		:modes,
		:menu,
		:gestures,
		:application_name,
		:application_long_name,
		:secondary_id,
		:include_buttons,
		:include_rings,
		:include_menu,
		:include_gestures

	serialize :buttons
	serialize :modes
	serialize :menu
	serialize :gestures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController
	def main
		@reco = Recommendation.find_by_id params[:id]
		filename = @reco.title.to_ascii.parameterize
		content = render_to_string :template => "download/main",
			:formats => [:xml], :layout => false
		send_data content,
			:type => 'text/xml',
			:disposition => "attachment; filename=#{filename}.wacomxs"
	end

	def raw
		@reco = Recommendation.find_by_id params[:id]
		render :template => 'download/main',
			:formats => [:xml], :layout => false
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
	# GET /recommendations
	# GET /recommendations.json
	def index
		@recommendations = Recommendation.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render :json => @recommendations.to_json(:only => [:id, :title, :created_at]) }
		end
	end

	# GET /recommendations/1
	# GET /recommendations/1.json
	def show
		@recommendation = Recommendation.find(params[:id])
		#sleep 1

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @recommendation }
		end
	end

	# GET /recommendations/new
	# GET /recommendations/new.json
	def new
		@recommendation = Recommendation.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @recommendation }
		end
	end

	# GET /recommendations/1/edit
	def edit
		@recommendation = Recommendation.find(params[:id])
	end

	# POST /recommendations
	# POST /recommendations.json
	def create
		@recommendation = Recommendation.new(params[:recommendation])
		#sleep 1
		#render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)

		respond_to do |format|
			if @recommendation.save
				format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
				format.json { render json: @recommendation, status: :created, location: @recommendation }
			else
				format.html { render action: "new" }
				format.json { render json: @recommendation.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /recommendations/1
	# PUT /recommendations/1.json
	def update
		@recommendation = Recommendation.find(params[:id])
		#sleep 1
		#render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)

		respond_to do |format|
			if @recommendation.update_attributes(params[:recommendation])
				format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @recommendation.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /recommendations/1
	# DELETE /recommendations/1.json
	def destroy
		@recommendation = Recommendation.find(params[:id])
		@recommendation.destroy

		respond_to do |format|
			format.html { redirect_to recommendations_url }
			format.json { head :no_content }
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/download_helper.rb
module DownloadHelper

	def tablet_models
		[
			300, # Cintiq 20WSX
			301, # Cintiq 12W (DTZ-1200)

			# I4
			321, # Medium
			322, # Large
			323, # XL
			324, # Wireless
			327, # Cintiq 24HD (Osprey Pen)
			328, # Cintiq 24HDT (Osprey Touch)
			330, # Cintiq 22HD (Osprey Pen Value)

			# I5
			335, # Medium Pen
			336, # Small Pen & Touch
			337, # Medium Pen & Touch
			338, # Large Pen & Touch
		]
	end

	def tablet_types
		[
			17, # PTZ USB
			24, # PTK USB
			26, # PTK BT
			27, # WL Receiver
		]
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/home/index.html.erb
<div class="navbar navbar-static-top">
	<div class="navbar-inner">
		<a class="brand" href="/"><img src="/logo.png"/></a>
		<ul class="nav pull-right">
			<li><a href="#" data-bind="click: doImport">Import</a></li>
			<li><a href="#" data-bind="click: doLoad">Open</a></li>
		</ul>
	</div>
</div>

<div class="container">

	<!-- Import view -->
	<div id="import" class="modal hide fade" data-bind="with: importVM">
		<div class="modal-header">
			<h3>Import</h3>
		</div>
		<div class="modal-body">
			<form>
				<input type="file" id="importfile" data-bind="file: filedata">

				<div data-bind="with: innerVM">
					<h4>Applications</h4>
					<!-- ko foreach: appArray -->
					<label class="radio">
						<input type="radio" name="appsGroup" data-bind="value: appId, checked: $parent.selectedAppId" />
						<span data-bind="text: name"></span>
					</label>
					<!-- /ko -->

					<h4>Tablets</h4>
					<!-- ko foreach: tablets -->
					<label class="radio">
						<input type="radio" name="tabsGroup" data-bind="value: name, checked: $parent.selectedTablet" />
						<span data-bind="text: name"></span>
					</label>
					<!-- /ko -->

				</div>
			</form>
			<div class="alert alert-error" data-bind="visible: error">
				<button type="button" class="close" data-dismiss="alert">×</button>
				There was an error.  Tell Ben.
			</div>
		</div>
		<div class="modal-footer">
			<img data-bind="visible: busy" src="/busy.gif" />
			<button class="btn" data-bind="click: cancel">Cancel</button>
			<button class="btn btn-primary" data-bind="css: {disabled: submitDisabled}, click: submit">
				Import
			</button>
		</div>
	</div>

	<!-- Load view -->
	<div id="load" class="modal hide fade" data-bind="with: loadVM">
		<div class="modal-header">
			<h3>Load</h3>
		</div>
		<div class="modal-body">
			<div data-bind="foreach: items">
				<a class="btn btn-block load-btn" data-bind="click: open">
					<span class="load-title" data-bind="text: displayTitle"></span>
					<span class="load-date" data-bind="text: displayDate"></span>
				</a>
			</div>
		</div>
		<div class="modal-footer">
			<button class="btn" data-bind="click: cancel">Cancel</button>
		</div>
	</div>

	<!-- Show view -->
	<form data-bind="with: showVM">
		<div class="row">
			<div class="span6">
				<label>Title</label>
				<input data-bind="value: title, valueUpdate: 'afterkeydown'" class="span6" placeholder="Title" />
				<label>Short name</label>
				<input data-bind="value: application_name" class="span6" />
				<label>Secondary ID</label>
				<input data-bind="value: secondary_id" class="span6" />
				<label>Long name</label>
				<input data-bind="value: application_long_name" class="span6" />
			</div>
			<div class="span4">
				<div class="well">
					<span style="display:none" data-bind="ifnot: has_buttons" class="span-2 muted">(No buttons configured)</span>
					<div class="span-2" data-bind="if: has_buttons">
						<label class="checkbox">
							<input type="checkbox" data-bind="checked: include_buttons">
							Include Buttons
						</label>
					</div>
					<i rel="buttons-popover" class="pull-right icon-info-sign" data-bind="visible: has_buttons"></i>
					<div id="buttons-popover" style="display:none">
						<div data-bind="foreach: buttons">
							<p>
							<span data-bind="text: buttonName"></span>:
							<span data-bind="buttonFunction: buttonFunction"></span>
							<span data-bind="visible: buttonFunction == '8', text: '(' + buttonKeystrokeShortcutName + ')'"></span>
							<span data-bind="if: buttonFunction == '9'">(<span data-bind="modifier: modifier"></span>)</span>
							</p>
						</div>
					</div>
				</div>
				<div class="well">
					<span style="display:none" data-bind="visible: !has_rings()" class="span-2 muted">(No rings configured)</span>
					<div class="span-2" data-bind="visible: has_rings">
						<label class="checkbox">
							<input type="checkbox" data-bind="checked: include_rings">
							Include Rings
						</label>
					</div>
					<i rel="modes-popover" class="pull-right icon-info-sign" data-bind="visible: has_rings"></i>
					<div id="modes-popover" style="display:none">
						<div data-bind="foreach: modes">
							<div>
								<h4 data-bind="text: name"></h4>
								<ul data-bind="foreach: modes">
									<li>
									<span data-bind="buttonFunction: touchStripFunction"></span>
									<span data-bind="visible: touchStripFunction == '8', text: '(' + touchStripKeystrokeName + ')'"></span>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="well">
					<span style="display:none" data-bind="visible: !has_menu()" class="span-2 muted">(No menu configured)</span>
					<div class="span-2" data-bind="visible: has_menu">
						<label class="checkbox">
							<input type="checkbox" data-bind="checked: include_menu">
							Include Radial Menu
						</label>
					</div>
					<i rel="menu-popover" class="pull-right icon-info-sign" data-bind="visible: has_menu"></i>
					<div id="menu-popover" style="display:none" data-bind="foreach: menu">
						<p>
						<span data-bind="text: name"></span>:
						<span data-bind="radialFunction: radialFunction"></span>
						</p>
					</div>
				</div>
				<div class="well">
					<span style="display:none" data-bind="visible: !has_gestures()" class="span-2 muted">(No gestures configured)</span>
					<div class="span-2" data-bind="visible: has_gestures">
						<label class="checkbox">
							<input type="checkbox" data-bind="checked: include_gestures">
							Include Gestures
						</label>
					</div>
					<i rel="gestures-popover" class="pull-right icon-info-sign" data-bind="visible: has_gestures"></i>
					<div id="gestures-popover" style="display:none;" data-bind="with: gestures">
						<ul class="unstyled">
							<!-- ko foreach: simple -->
							<li><small><span data-bind="text: name"></span>: <span data-bind="text: value"></span></small></li>
							<!-- /ko -->
							<!-- ko foreach: complex -->
							<li><small><span data-bind="text: name"></span>: (...)</small></li>
							<!-- /ko -->
						</ul>
					</div>
				</div>
			</div>
			<div class="span2">
				<button class="btn btn-success btn-block" data-bind="click: save, visible: dirty">Save</button>
				<a class="btn btn-primary btn-block" data-bind="attr: {href: urlForDownload}, visible: !dirty()">
					Download
				</a>
				<button class="btn btn-danger btn-block" data-bind="click: destroy">Delete</button>
			</div>
		</div>

		<div class="row results">
			<div class="span6 offset3">
				<img data-bind="visible: busy" src="/busy.gif" />
				<div data-bind="foreach: alerts">
					<div class="alert" data-bind="css: alertType">
						<button type="button" class="close" data-bind="click: $parent.removeAlert">&times;</button>
						<span data-bind="text: displayText"></span>
					</div>
				</div>
			</div>
		</div>

	</form>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Wacom XS</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<%= yield %>

	</body>
</html>

app/views/recommendations/_form.html.erb
<%= form_for(@recommendation) do |f| %>
	<% if @recommendation.errors.any? %>
		<div id="error_explanation">
			<h><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h>

			<ul>
				<% @recommendation.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="actions">
		<%= label_tag(:title, "Title") %>
		<%= f.text_field :title %>
		<br>
		<%= f.submit %>
	</div>
<% end %>

app/views/recommendations/edit.html.erb
<h1>Editing recommendation</h1>

<%= render 'form' %>

<%= link_to 'Show', @recommendation %> |
<%= link_to 'Back', recommendations_path %>

app/views/recommendations/index.html.erb
<h1>Listing recommendations</h1>

<table>
	<tr>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @recommendations.each do |recommendation| %>
		<tr>
			<td><%= recommendation.title %></td>
			<td><%= link_to 'Show', recommendation %></td>
			<td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
			<td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<br />

<%= link_to 'New Recommendation', new_recommendation_path %>

app/views/recommendations/new.html.erb
<h1>New recommendation</h1>

<%= render 'form' %>

<%= link_to 'Back', recommendations_path %>

app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<script>
	$(function() {
		window.recommendation = new Recommendation(
		<%= raw @recommendation.to_json %>
		);
		ko.applyBindings(window.recommendation);
	});
</script>



<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back', recommendations_path %>